
export const RulesFieldKey = '__hs_rules__'
export const ActionFieldKey = '__hs_action__'
export const SelectedRowFieldKeys = '__hs_selectedRowKeys__'
export const DarkFieldKey = '__hs_dark__'
export const IndexFieldKey = '__hs_index__'
export const HiddenFieldsFieldKey = '__hs_hiddenFields__'
export const PathFieldKey = '__hs_path__'

export const SyncDataMsgKey = '__hs_syncdata__'
export const UpdateMsgKey = '__hs_update__'
export const CountMsgKey = '__hs_count__'
export const ResponseMsgKey = '__hs_response__'
export const PagescriptMsgKey = '__hs_pagescript__'
export const StorageMsgKey = '__hs_storage__'
export const LogMsgKey = '__hs_log__'
export const BackgroundMsgKey = '__hs_background__'
export const IframeMsgKey = '__hs_iframe__'